apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.name }}-intention-config
  labels:
    helm.sh/chart: {{ .Values.global.name }}
    app: {{ .Values.global.name }}
data:
  intention.json: |-
    {
      "event": {
        "provider": "provision-secret-demo",
        "reason": "Job triggered",
        "url": "JOB_URL"
      },
      "actions": [
        {
          "action": "package-provision",
          "id": "provision",
          "provision": ["approle/secret-id"],
          "service": {
            "name": "spar-war",
            "project": "spar",
            "environment": "test"
          }
        }
      ],
      "user": {
        "name": "gruan@azureidir"
      }
    }