global:
  name: "knox-retriever-demo"
  namespace: "c2053d"
  short-env: "dev"

server:
  image:
    registry: "artifacts.developer.gov.bc.ca/github-docker-remote/"
    context: "bcgov/nr-broker-openshift-knox-retriever"
  route:
    internal:
      enabled: true
      host: nestapp-test.apps.silver.devops.gov.bc.ca
vault:
  secret: "vault-secret"
  storage:
    classname: "netapp-file-backup"
    backup: "500Mi"

app:
  version: "1.0.1"