name: Build and Push Nest App Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: test # Use the 'test' environment for secrets

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/nest-app

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./nest-app # Path to the Dockerfile
          push: true # Push the image to GitHub Container Registry
          tags: |
            ${{ env.IMAGE_NAME }}:test
          build-args: |
            VAULT_ADDR=${{ secrets.VAULT_ADDR }}
            ENVCONSUL_VERSION=0.13.1