name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
    paths:
      - 'generate-token/**' # Trigger only when files in the ./generate-token folder change

  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - 'generate-token/**' # Trigger only when files in the ./generate-token folder change

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/nr-broker-openshift-knox-retriever

jobs:
  # Job for building and pushing the image for the production environment
  build-and-push:
    name: Build and Push Docker Image for Production
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Production Image
        uses: docker/build-push-action@v5
        with:
          context: ./generate-token
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
          build-args: |
            BROKER_URL=${{ vars.BROKER_URL }}
            VAULT_ADDR=${{ vars.VAULT_ADDR }}