name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*"
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/nr-broker-openshift-knox-retriever

jobs:
  # Job for building and pushing the image for the test environment
  build-and-push-test:
    name: Build and Push Docker Image for Test
    runs-on: ubuntu-latest
    environment: test # Use the 'test' environment for secrets
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Test Image
        uses: docker/build-push-action@v5
        with:
          context: ./generate-token
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:test
          build-args: |
            BROKER_URL=${{ secrets.BROKER_URL }}
            VAULT_ADDR=${{ secrets.VAULT_ADDR }}

  # Job for building and pushing the image for the production environment
  build-and-push-prod:
    name: Build and Push Docker Image for Production
    runs-on: ubuntu-latest
    environment: prod # Use the 'production' environment for secrets
    needs: build-and-push-test # Ensure this job runs after the test job
    if: startsWith(github.ref, 'refs/tags/v') # Only run for tags starting with 'v'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Production Image
        uses: docker/build-push-action@v5
        with:
          context: ./generate-token
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
          build-args: |
            BROKER_URL=${{ secrets.BROKER_URL }}
            VAULT_ADDR=${{ secrets.VAULT_ADDR }}