name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

jobs:
  # Job for building and pushing the image for the production environment
  build-on-pull-request:
    name: Build Docker Image on PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push nr-broker-openshift-knox-retriever Production Image
        uses: docker/build-push-action@v5
        with:
          context: ./generate-token
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/nr-broker-openshift-knox-retriever:${{ github.event.number }}-backend
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BROKER_URL=${{ vars.BROKER_URL }}
            VAULT_ADDR=${{ vars.VAULT_ADDR }}
      
      - name: Build and Push nest-app Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./nest-app 
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/nest-app:${{ github.event.number }}-frontend
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VAULT_ADDR=${{ vars.VAULT_ADDR }}
            ENVCONSUL_VERSION=0.13.1