name: Tag Main

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - ".**"
      - "**.md"
      - "**.yml"
      - "**.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    name: Build and Push Docker Image on tag
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=ref,event=pr
            type=raw,value=${{ github.ref_name }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push nr-broker-openshift-knox-retriever Production Image
        uses: docker/build-push-action@v5
        with:
          context: ./generate-token
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/nr-broker-openshift-knox-retriever:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          build-args: |
            BROKER_URL=${{ vars.BROKER_URL }}
            VAULT_ADDR=${{ vars.VAULT_ADDR }}
      
      - name: Build and Push nest-app Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./nest-app 
          push: true 
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/nest-app:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          build-args: |
            VAULT_ADDR=${{ vars.VAULT_ADDR }}
            ENVCONSUL_VERSION=0.13.1